name: auto-merge

on:
  pull_request_target:

permissions:
  contents: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - uses: ahmadnassri/action-dependabot-auto-merge@5d98f10d910782d0bb431fc03ae26532543ae184 # v2.6.0
        with:
          target: minor
          command: squash and merge
          github-token: ${{ secrets.ADOPTIUM_BOT_TOKEN }}
